### ISSUE TITLE
Blocks on startup

### ISSUE THREAD

**Issue by ysangkok** [EricSmekens/node-serial-obd#10]
Somehow the autodetection of USB serial port is not working. Both python-OBD and freediag worked somehow. I have recorded an strace in script(1): https://hushfile.it/562fc6cc48b49#A2fhK6lEKENI1KMkKFPm8VLs-R4JF1hlvp6leSaH

I do not know if it is helpful to you, maybe I can help some other way.

**Comment by EricSmekens** [comment]
Could you post the code you are using to get to this problem?

**Comment by ysangkok** [comment]
I am using the code from the "basic usage" example in the readme, but I changed the path to `/dev/ttyUSB0`.

**Comment by EricSmekens** [comment]
Currently lack a simulator and a bit of time/interest, so just to let you know I am not looking into it at this moment. Sorry.

**Comment by ysangkok** [comment]
Thanks for the feedback. I'll close this so it doesn't clutter.
