### ISSUE TITLE
Send OBD 0902 VIN command over WiFi

### ISSUE THREAD

**Issue by bmwertman** [EricSmekens/node-serial-obd#9]
I have been able to connect to my Wifi OBDII adapter using [Matt Parson's WifiWizard](https://github.com/parsonsmatt/WifiWizard) library. But because I'm writing a AngularJS/ionic application for Android I am not able to use your node module directly for sending and receiving OBDII commands.

I tried unsuccessfully to use [browserify CDN](https://www.brcdn.org/) to make the library available on the client side. I really only need to be able to pull the vehicle's VIN number though so this all seems like overkill. Can you recommend a way of implementing this?

**Comment by EricSmekens** [comment]
I was on a holiday. I will check this in some days!

**Comment by EricSmekens** [comment]
You might be right that it seems a bit overkill if you only want to access the VIN.

With browserify, I assume it will not work, because the module needs access to a serial port, which I assume this will not work. (Maybe Ionic has support, but I do not have any knowledge with that.)

When you have some more info, please provide a good idea which could be a solution to your problem.

**Comment by bmwertman** [comment]
It seems I need to send the AT 0902 command via TCP. I have the ip address of my wifi adapter and the port that it uses. I was looking at trying to use the [Chrome sockets library](https://evothings.com/doc/raw/plugins/developer.chrome.com/apps/sockets_tcp#method-connect) to create the TCP connection to be able to write the command. 

I found this [cordova wrapper for the Chrome sockets](https://github.com/MobileChromeApps/cordova-plugin-chrome-apps-sockets-tcp). But need to update cordova to support it.

**Comment by bmwertman** [comment]
Updated Cordova and got it installed. I'm able to open a TCP port which on connection sends back a string stating that I've connected to the wifi adapter. However the Chrome socket TCP send method wants the data wrapped in an array buffer. I tried using this function to package the data but wasn't sure if it should be 8 or 16 bit

```
$scope.strToArrBuffer = function (str)  {
    var buf = new ArrayBuffer(str.length*2); // 2 bytes for each char
    var bufView = new Uint8Array(buf);//convert to 8 bit array
    for (var i=0, strLen=str.length; i<strLen; i++) {
      bufView[i] = str.charCodeAt(i);//convert to ascii
    }
    return buf;
  }
```
also not sure if the adapter or obd would know what to do with an array buffer or if it just expects an ascii string.

**Comment by bmwertman** [comment]
I'm now able to send a request using the fore mentioned library. And I get a response back, albeit not a very useful one. It's the same as the request I'm sending "0902/r". Any suggestions?

**Comment by EricSmekens** [comment]
So basically it echoes back your request?
And nothing more? Because I would atleast expect a response back. (Atleast something else than your 0902. Does it behave differently when you try this with another app or just by terminal or something like that?

**Comment by bmwertman** [comment]
Yes, it just echoes it back. I've tried sending the disable echo command 'ATE0' first. That made no difference. I've tried sending my OBD VIN request as '0902', '0902/r', '0902 /r', '0902 5'(to tell OBD I'm expecting the VIN back in five lines), '0902 5 /r', '090205', 090205/r'. It always echoes back exactly what I send. 

The host light on the OBDLink MX Wifi flickers so I know it's seeing the request. The OBD light never does though so either the adapter isn't relaying the signal or the [OBD Emulator](http://freematics.com/pages/products/freematics-obd-emulator-mk2/) isn't responding. I've used the adapter in a car before to send commands using a GUI. So I know it works. I wouldn't know where to begin to ry to do this through the terminal. Here is my code if you want to have a look;
```
 function ab2str(buf) {
    return String.fromCharCode.apply(null, new Uint8Array(buf));
  }

  function str2ab(str) {
    var buf = new ArrayBuffer(str.length*2); // 2 bytes for each char
    var bufView = new Uint8Array(buf);
    for (var i=0, strLen=str.length; i<strLen; i++) {
      bufView[i] = str.charCodeAt(i);
    }
    return buf;
  }
```
```
$cordovaWifiWizard.connectNetwork(config.SSID)//connect to OBDII plug
            .then(function (res){
              $scope.OBDConnected = true;
              var PID = str2ab("0902 5");
              // var disableEcho = str2ab("ATE0");
              var createAttempts = 0;
              tcpCreate();
              function tcpCreate(){
                chrome.socket.create("tcp", function (object){
                  console.log(object);
                  chrome.socket.connect(object.socketId, '192.168.0.10', 35000, function (result){
                    console.log(result);
                    if(result === -1000 && createAttempts < 5){
                      chrome.socket.destroy(object.socketId);
                      console.log("Didn't connect! Trying again.");
                      $timeout(function(){
                        createAttempts++
                        tcpCreate();
                      }, 800);
                    } else if(result === -1000 && createAttempts === 5) { 
                      console.log("Somethings wrong");
                    } else {
                      chrome.socket.getInfo(object.socketId, function (obj){
                        console.log(obj);       
                        // chrome.socket.write(object.socketId, disableEcho, function (writeInfo){
                        //   console.log(writeInfo);
                        //   chrome.socket.read(object.socketId, function (recvFromInfo){
                        //     console.log(recvFromInfo);
                        $timeout(function(){
                          chrome.socket.write(object.socketId, PID, function (writeInfo){
                            console.log(writeInfo);
                            chrome.socket.read(object.socketId, function (recvFromInfo){
                              console.log(recvFromInfo);
                              console.log(ab2str(recvFromInfo.data));
                              chrome.socket.disconnect(object.socketId);
                              chrome.socket.destroy(object.socketId);
                            });
                          });
                        }, 500);
                        //   });   
                        // });
                      });
                    }
                  });
                }); 
              }
```

**Comment by Munnster83** [comment]
hi bmwertman, did you ever get this working as I have the same issues :(

**Comment by EricSmekens** [comment]
@bmwertman Just to send a notice :)
